# Generated by Django 4.2.29 on 2026-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_vector_embedding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chatbot_cha_session_24e989_idx',
            old_name='chatbot_chatmessage_session_created_idx',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number with country code', max_length=30),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='preference',
            field=models.CharField(blank=True, choices=[('property', 'Property'), ('services', 'Services')], help_text='What the visitor is looking for', max_length=32),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_name',
            field=models.CharField(blank=True, help_text='Name provided during onboarding', max_length=128),
        ),
        migrations.AlterField(
            model_name='propertyembedding',
            name='source_text',
            field=models.TextField(blank=True, help_text='Text that was embedded'),
        ),
    ]
