# Generated by Django 6.0.3 on 2026-04-03 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('property_name', models.CharField(help_text='e.g., 3BHK Apartment, Koramangala', max_length=255)),
                ('property_address', models.TextField()),
                ('package', models.CharField(choices=[('starter', 'Shield Starter'), ('pro', 'Shield Pro'), ('complete', 'Shield Complete')], default='pro', max_length=20)),
                ('advocate_name', models.CharField(blank=True, help_text='e.g., Adv. S. Ramesh', max_length=255, null=True)),
                ('advocate_notes', models.TextField(blank=True, null=True)),
                ('verdict', models.CharField(choices=[('pending', 'Pending'), ('green', 'Green — Safe to proceed'), ('yellow', 'Yellow — Caution'), ('red', 'Red — Do not proceed')], default='pending', max_length=15)),
                ('verdict_summary', models.TextField(blank=True, help_text='E.g. No critical issues detected · 12 checks passed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('done', 'Done')], default='pending', max_length=10)),
                ('order_idx', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='legal_services.legalorder')),
            ],
            options={
                'ordering': ['order_idx'],
            },
        ),
        migrations.CreateModel(
            name='VerdictCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_passed', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdict_checks', to='legal_services.legalorder')),
            ],
        ),
    ]
