# Generated by Django 6.0.3 on 2026-04-03 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalorder',
            name='advocate_name',
        ),
        migrations.AddField(
            model_name='legalorder',
            name='advocate',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'advocate'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
