# Generated by Django 6.0.3 on 2026-04-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0002_remove_legalorder_advocate_name_legalorder_advocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalorder',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Transaction / UTR / Razorpay ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legalorder',
            name='payment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalorder',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Screenshot or receipt image', null=True, upload_to='legal_payments/'),
        ),
        migrations.AddField(
            model_name='legalorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Payment Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=15),
        ),
    ]
