# Generated by Django 6.0.3 on 2026-04-03 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0003_legalorder_payment_id_legalorder_payment_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('assignment', 'Advocate Assignment'), ('step', 'Step Update'), ('verdict', 'Verdict Update'), ('payment', 'Payment Update'), ('package', 'Package Change'), ('system', 'System')], default='system', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_activities', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='legal_services.legalorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
