# Generated by Django 6.0.3 on 2026-04-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0004_orderactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderactivity',
            name='category',
            field=models.CharField(choices=[('assignment', 'Advocate Assignment'), ('step', 'Step Update'), ('verdict', 'Verdict Update'), ('payment', 'Payment Update'), ('package', 'Package Change'), ('note', 'Message to Client'), ('client_note', 'Message from Client'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
