# Generated by Django 6.0.3 on 2026-03-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('initials', models.CharField(blank=True, max_length=8)),
                ('tagline', models.CharField(blank=True, max_length=256)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=256)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('established', models.CharField(blank=True, max_length=64)),
                ('workforce', models.CharField(blank=True, max_length=64)),
                ('presence', models.CharField(blank=True, max_length=256)),
                ('listed_on', models.CharField(blank=True, max_length=128)),
                ('contact', models.CharField(blank=True, max_length=64)),
                ('about_p1', models.TextField(blank=True)),
                ('about_p2', models.TextField(blank=True)),
                ('about_p3', models.TextField(blank=True)),
            ],
        ),
    ]
