# Generated by Django 6.0.3 on 2026-04-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
