# Generated by Django 4.2.29 on 2026-04-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_remove_developer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(help_text='e.g. SANJEEVINI', max_length=100)),
                ('developer_subtitle', models.CharField(blank=True, help_text='e.g. GROUP or ESTANCIA', max_length=100)),
                ('rera_text', models.CharField(blank=True, max_length=255)),
                ('headline', models.CharField(help_text='Main headline text', max_length=200)),
                ('headline_highlight', models.CharField(blank=True, help_text='Specific word in headline to highlight', max_length=100)),
                ('subheadline', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(help_text='Background hero image.', upload_to='hero_sliders/')),
                ('explore_link', models.URLField(blank=True, help_text='URL for the Explore Now button', max_length=500)),
                ('qr_data', models.CharField(blank=True, help_text='Data/URL to encode in the QR code', max_length=255)),
                ('is_dark_background', models.BooleanField(default=True, help_text='Check this if the background is dark (uses white text)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
