# Generated by Django 6.0.3 on 2026-04-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional background image optimized specifically for mobile (portrait) screens.', null=True, upload_to='hero_sliders/mobile/'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=models.ImageField(help_text='Background hero image (Desktop).', upload_to='hero_sliders/'),
        ),
    ]
