# Generated by Django 6.0.3 on 2026-04-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_heroslider_mobile_image_alter_heroslider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='developer_name',
            field=models.CharField(blank=True, help_text='e.g. SANJEEVINI', max_length=100),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='headline',
            field=models.CharField(blank=True, help_text='Main headline text', max_length=200),
        ),
    ]
