# Generated by Django 6.0.3 on 2026-04-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_heroslider_developer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='internal_name',
            field=models.CharField(default='Untitled Slide', help_text='Admin-only name to identify this slide. Not visible to users.', max_length=100),
        ),
    ]
