# Generated by Django 6.0.3 on 2026-04-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_heroslider_internal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='show_explore_button',
            field=models.BooleanField(default=True, help_text="Display the visible 'Explore Now' button on this slide."),
        ),
    ]
