# Generated by Django 4.2.29 on 2026-03-22 16:38

from django.db import migrations, models


def nullify_blank_phones(apps, schema_editor):
    """Convert empty-string phones to NULL before adding the unique constraint."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(phone='').update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_phone_otp'),
    ]

    operations = [
        # Step 1: allow NULLs (no unique yet — old empty strings are still '')
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        # Step 2: convert '' → NULL so duplicates don't block the unique constraint
        migrations.RunPython(nullify_blank_phones, migrations.RunPython.noop),
        # Step 3: now safe to add unique + db_index
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
