# Generated by Django 6.0.3 on 2026-04-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_profile_complete_and_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('agent', 'Agent'), ('admin', 'Admin'), ('advocate', 'Advocate')], default='buyer', max_length=10),
        ),
    ]
