# Generated by Django 6.0.3 on 2026-04-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_bar_number_user_is_approved_advocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_image',
            field=models.ImageField(blank=True, null=True, upload_to='advocate_docs/aadhaar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='advocate_docs/address/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bar_council_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='advocate_docs/bar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='advocate_docs/pan/'),
        ),
    ]
