# Generated by Django 6.0.3 on 2026-04-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_aadhaar_image_user_address_proof_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pan_image',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
