# Generated by Django 6.0.3 on 2026-04-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_pan_image_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('agent', 'Agent'), ('admin', 'Admin'), ('legal_admin', 'Legal Admin'), ('advocate', 'Advocate')], default='buyer', max_length=20),
        ),
    ]
