# Generated by Django 4.2.29 on 2026-04-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('agent', 'Agent'), ('admin', 'Admin'), ('legal_admin', 'Legal Admin'), ('advocate', 'Advocate'), ('customer_support', 'Customer Support')], default='buyer', max_length=20),
        ),
    ]
