# Generated by Django 4.2.29 on 2026-03-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='key_takeaways',
            field=models.TextField(blank=True, help_text='One takeaway per line. Displayed as a bullet list at the start of the article.'),
        ),
    ]
