# Generated by Django on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_to_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Override the title used for SEO (max 60 chars).', max_length=60),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Override the excerpt used for SEO description (max 160 chars).', max_length=160),
        ),
    ]
