# Generated by Django 4.2.29 on 2026-03-16 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent'), ('new_project', 'New Project'), ('commercial', 'Commercial')], default='buy', max_length=20)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('plot', 'Plot / Land'), ('office', 'Office Space'), ('shop', 'Shop / Retail'), ('warehouse', 'Warehouse')], default='apartment', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('bhk', models.CharField(blank=True, choices=[('studio', 'Studio'), ('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK'), ('5bhk', '5 BHK'), ('6+bhk', '6+ BHK')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_label', models.CharField(blank=True, help_text='e.g. "/ Onwards", "/ Month"', max_length=50)),
                ('price_on_req', models.BooleanField(default=False, verbose_name='Price on Request')),
                ('address', models.TextField()),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(default='Bengaluru', max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('area_sqft', models.PositiveIntegerField(blank=True, null=True, verbose_name='Area (sq.ft)')),
                ('carpet_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carpet Area (sq.ft)')),
                ('floor_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('furnishing', models.CharField(blank=True, choices=[('furnished', 'Fully Furnished'), ('semi', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], max_length=15)),
                ('facing', models.CharField(blank=True, help_text='e.g. East, North-East', max_length=50)),
                ('age_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Property Age (years)')),
                ('parking_slots', models.PositiveSmallIntegerField(default=0)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_signature', models.BooleanField(default=False, help_text='Ultra-premium / Signature collection')),
                ('is_new', models.BooleanField(default=True)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented'), ('pending', 'Pending Approval'), ('draft', 'Draft'), ('inactive', 'Inactive')], default='draft', max_length=15)),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='agents.agent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or SVG name', max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.property')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.ManyToManyField(blank=True, to='properties.propertytag'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['listing_type', 'status'], name='properties__listing_c2c341_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'locality'], name='properties__city_23f8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured', 'is_signature'], name='properties__is_feat_0308c5_idx'),
        ),
    ]
