# Generated by Django 4.2.29 on 2026-03-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='properties/floor_plans/', verbose_name='Floor Plan Image'),
        ),
    ]
