# Generated by Django 4.2.29 on 2026-03-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_floor_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('coop', 'Co-operative Society'), ('poa', 'Power of Attorney')], max_length=15, verbose_name='Ownership Type'),
        ),
        migrations.AddField(
            model_name='property',
            name='rera_approved',
            field=models.BooleanField(default=False, verbose_name='RERA Approved'),
        ),
        migrations.AddField(
            model_name='property',
            name='rera_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='RERA Registration No.'),
        ),
    ]
