# Generated by Django 4.2.29 on 2026-03-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_floorplan_image_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyfeature',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload an icon image (PNG/SVG recommended, ~64×64px)', upload_to='features/'),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS icon class or SVG markup', max_length=100),
        ),
    ]
