# Generated by Django 4.2.29 on 2026-03-28 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_add_feature_icon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectivityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transit', 'Transit'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('lifestyle', 'Lifestyle'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(help_text='e.g. Whitefield Metro Station', max_length=200)),
                ('distance', models.CharField(help_text='e.g. 2.5 km, 10 min drive', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectivity', to='properties.property')),
            ],
            options={
                'verbose_name': 'Connectivity Item',
                'verbose_name_plural': 'Connectivity Items',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
