# Generated by Django 6.0.3 on 2026-03-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_add_connectivity_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='developer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Developer / Builder'),
        ),
    ]
