# Generated by Django 6.0.3 on 2026-03-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_developer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='developers/logos/')),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('established_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, help_text='e.g. Bengaluru, Pan India', max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='developer_name',
        ),
        migrations.AddField(
            model_name='property',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.developer', verbose_name='Developer / Builder'),
        ),
    ]
