# Generated by Django 6.0.3 on 2026-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_developer_remove_property_developer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g. Premium, Affordable, Commercial, Luxury, Township, Plotted)', max_length=255),
        ),
    ]
