# Generated by Django 4.2.29 on 2026-04-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_developer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='construction_status',
            field=models.CharField(blank=True, choices=[('ready', 'Ready to Move'), ('under_construction', 'Under Construction'), ('new_launch', 'New Launch')], max_length=20, verbose_name='Construction Status'),
        ),
        migrations.AddField(
            model_name='property',
            name='four_wheeler_parking',
            field=models.BooleanField(default=False, verbose_name='4-Wheeler Parking'),
        ),
        migrations.AddField(
            model_name='property',
            name='two_wheeler_parking',
            field=models.BooleanField(default=False, verbose_name='2-Wheeler Parking'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bhk',
            field=models.CharField(blank=True, choices=[('studio', 'Studio'), ('1rk', '1 RK'), ('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK'), ('5bhk', '5 BHK'), ('6+bhk', '6+ BHK')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('independent_house', 'Independent House/Villa'), ('gated_villa', 'Gated Community Villa'), ('standalone', 'Standalone Building'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('plot', 'Plot / Land'), ('office', 'Office Space'), ('shop', 'Shop / Retail'), ('warehouse', 'Warehouse')], default='apartment', max_length=20),
        ),
    ]
