# Generated by Django 4.2.29 on 2026-04-09 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_add_construction_status_parking_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong_price', 'Wrong Price'), ('wrong_location', 'Wrong Location'), ('fake_listing', 'Fake / Duplicate Listing'), ('wrong_details', 'Incorrect Details'), ('already_sold', 'Already Sold / Rented'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Report',
                'verbose_name_plural': 'Property Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
