# Generated by Django 6.0.3 on 2026-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_add_property_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lock_in_period',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Lock-in period in years', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly maintenance', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='power_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant_preference',
            field=models.CharField(blank=True, choices=[('any', 'Anyone'), ('family', 'Family Only'), ('bachelors', 'Bachelors Only'), ('company', 'Company Lease')], max_length=15),
        ),
    ]
