# Generated by Django 4.2.29 on 2026-04-09 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0014_property_available_from_property_lock_in_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='auto_delete_at',
            field=models.DateTimeField(blank=True, help_text='Rejected listings are auto-deleted after 30 days.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='fix_notes',
            field=models.TextField(blank=True, help_text='Notes sent back to owner when requesting a fix.'),
        ),
        migrations.AddField(
            model_name='property',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason shown to the listing owner on rejection.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented'), ('pending', 'Pending Approval'), ('draft', 'Draft'), ('inactive', 'Inactive'), ('rejected', 'Rejected'), ('needs_fix', 'Needs Fix')], default='draft', max_length=15),
        ),
    ]
