# Generated by Django 6.0.3 on 2026-04-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_add_rejection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_negotiable',
            field=models.BooleanField(default=False, verbose_name='Price Negotiable'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_verified',
            field=models.BooleanField(default=False, verbose_name='Title Verified'),
        ),
    ]
