# Generated by Django 4.2.29 on 2026-04-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_property_is_negotiable_property_title_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectivityitem',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='SVG sprite icon ID, e.g. i-near-metro', max_length=100),
        ),
    ]
