# Generated by Django 4.2.29 on 2026-04-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_add_connectivity_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tenant_preference',
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('new_project', 'New Project'), ('commercial', 'Commercial')], default='buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('pending', 'Pending Approval'), ('draft', 'Draft'), ('inactive', 'Inactive'), ('rejected', 'Rejected'), ('needs_fix', 'Needs Fix')], default='draft', max_length=15),
        ),
    ]
