# Generated by Django 4.2.29 on 2026-04-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_remove_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lock_in_period',
        ),
        migrations.RemoveField(
            model_name='property',
            name='maintenance_charge',
        ),
        migrations.RemoveField(
            model_name='property',
            name='power_backup',
        ),
        migrations.RemoveField(
            model_name='property',
            name='security_deposit',
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('new_project', 'New Project')], default='buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('independent_house', 'Independent House/Villa'), ('gated_villa', 'Gated Community Villa'), ('standalone', 'Standalone Building'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('plot', 'Plot / Land')], default='apartment', max_length=20),
        ),
    ]
