# Generated by Django 4.2.29 on 2026-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_remove_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='show_in_explore',
            field=models.BooleanField(db_index=True, default=False, help_text='Display this property in the Explore Properties grid on the home page.', verbose_name='Show in Explore Section'),
        ),
    ]
