# Generated by Django 4.2.29 on 2026-04-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_add_show_in_explore'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_group_buy',
            field=models.BooleanField(default=False, verbose_name='Group Buy Available'),
        ),
    ]
