# Generated by Django 4.2.29 on 2026-04-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_property_has_group_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='has_group_buy',
            field=models.BooleanField(default=True, verbose_name='Group Buy Available'),
        ),
    ]
