# Generated by Django 4.2.29 on 2026-04-21 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0022_alter_property_has_group_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='group_buy_participants',
            field=models.ManyToManyField(blank=True, related_name='group_buys_joined', to=settings.AUTH_USER_MODEL, verbose_name='Group Buy Participants'),
        ),
    ]
