# Generated by Django 6.0.3 on 2026-04-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_property_group_buy_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL for the property tour', verbose_name='Video Tour URL'),
        ),
    ]
