# Generated by Django 4.2.29 on 2026-04-04 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0003_email_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Team member responsible for follow-up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled follow-up date/time', null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='source',
            field=models.CharField(blank=True, help_text='Page or section the form was submitted from', max_length=120),
        ),
    ]
