# Generated by Django 4.2.29 on 2026-04-04 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0004_add_source_assigned_followup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('comment', 'Comment'), ('status_change', 'Status Change'), ('followup_set', 'Follow-up Scheduled'), ('assigned', 'Assigned'), ('system', 'System')], default='comment', max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_activities', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='enquiries.enquiry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
