# Generated by Django 4.2.29 on 2026-04-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_add_enquiry_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='first_response_at',
            field=models.DateTimeField(blank=True, help_text='When first agent action was taken on this ticket', null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
