# Generated by Django 4.2.29 on 2026-04-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0007_remove_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('buy', 'Buy Property'), ('sell', 'Sell / List Property'), ('home_loan', 'Home Loan'), ('legal', 'Property Legal'), ('security', 'Security Services'), ('home_service', 'Home Services'), ('group_buy', 'Group Buy'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
