# Generated by Django 4.2.29 on 2026-03-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('developer_name', models.CharField(max_length=200)),
                ('developer_logo', models.ImageField(blank=True, null=True, upload_to='campaigns/logos/')),
                ('accent_color', models.CharField(default='#4A90C4', help_text='Hex colour, e.g. #4A90C4', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nav_style', models.CharField(choices=[('cobranded', 'Co-branded (HOMEXO + Developer)'), ('branded', 'Developer Branded (dark nav)'), ('minimal', 'Minimal (logo + CTA only)'), ('homexo', 'HOMEXO Default')], default='cobranded', max_length=20)),
                ('nav_cta_text', models.CharField(default='Book a Site Visit', max_length=80)),
                ('nav_show_links', models.BooleanField(default=True, help_text='Show nav links (About / Properties / Contact)')),
                ('hero_heading', models.CharField(help_text='Use | to split into two lines, e.g. "Discover|Prestige"', max_length=200)),
                ('hero_sub', models.CharField(blank=True, max_length=300)),
                ('hero_bg', models.ImageField(blank=True, help_text='Optional hero background image (falls back to gradient)', null=True, upload_to='campaigns/heroes/')),
                ('offer_label', models.CharField(blank=True, max_length=120)),
                ('offer_expiry', models.DateTimeField(blank=True, help_text='If set, a countdown timer appears on the detail page', null=True)),
                ('about_heading', models.CharField(blank=True, max_length=200)),
                ('about_body', models.TextField(blank=True)),
                ('cta_heading', models.CharField(blank=True, max_length=200)),
                ('cta_sub', models.CharField(blank=True, max_length=300)),
                ('cta_button_text', models.CharField(blank=True, default='Book a Free Consultation', max_length=80)),
                ('footer_style', models.CharField(choices=[('branded', 'Developer Branded Footer'), ('homexo', 'Full HOMEXO Footer'), ('minimal', 'Minimal (copyright bar only)')], default='branded', max_length=20)),
                ('footer_tagline', models.CharField(blank=True, max_length=300)),
                ('footer_address', models.TextField(blank=True)),
                ('footer_email', models.EmailField(blank=True, max_length=254)),
                ('footer_facebook', models.URLField(blank=True)),
                ('footer_instagram', models.URLField(blank=True)),
                ('footer_youtube', models.URLField(blank=True)),
                ('footer_copyright', models.CharField(blank=True, help_text='Leave blank to auto-generate "© 2026 <developer_name>. Powered by HOMEXO."', max_length=250)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='agents.agent')),
                ('properties', models.ManyToManyField(blank=True, related_name='campaigns', to='properties.property')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='✓', help_text='Unicode character or emoji used as the bullet icon', max_length=10)),
                ('heading', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
