# Generated by Django 6.0.3 on 2026-03-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_seed_villa_plot_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Image shown beside the about text', null=True, upload_to='campaigns/about/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='disclaimer',
            field=models.TextField(blank=True, help_text='Legal disclaimer shown at the bottom of the page'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='footer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location_body',
            field=models.TextField(blank=True, help_text='Rich description of connectivity (roads, metro, airport, etc.)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location_map_embed',
            field=models.TextField(blank=True, help_text='Google Maps embed iframe HTML (optional, used instead of image if provided)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location_map_image',
            field=models.ImageField(blank=True, help_text='Location / connectivity map image', null=True, upload_to='campaigns/maps/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='masterplan_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='masterplan_heading',
            field=models.CharField(blank=True, default='Overall Master Plan', max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='masterplan_image',
            field=models.ImageField(blank=True, help_text='Master plan / layout image', null=True, upload_to='campaigns/masterplans/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='stat_configs',
            field=models.CharField(blank=True, help_text='e.g. 1, 2, 3 & 4 BHK', max_length=120),
        ),
        migrations.AddField(
            model_name='campaign',
            name='stat_floors',
            field=models.CharField(blank=True, help_text='e.g. 3B + G + 19', max_length=80),
        ),
        migrations.AddField(
            model_name='campaign',
            name='stat_land_parcel',
            field=models.CharField(blank=True, help_text='e.g. 21 Acres', max_length=80),
        ),
        migrations.AddField(
            model_name='campaign',
            name='stat_possession',
            field=models.CharField(blank=True, help_text='e.g. Dec 2029+', max_length=80),
        ),
        migrations.AddField(
            model_name='campaign',
            name='stat_price_start',
            field=models.CharField(blank=True, help_text='e.g. ₹1.1 Crore Onwards*', max_length=80),
        ),
        migrations.CreateModel(
            name='CampaignAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='✦', help_text='Emoji or short label (GYM, POOL, etc.)', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='campaigns.campaign')),
            ],
            options={
                'verbose_name_plural': 'Campaign amenities',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(help_text='e.g. 2 BHK (L)', max_length=80)),
                ('sba_range', models.CharField(blank=True, help_text='e.g. 1250 – 1300 sft', max_length=120)),
                ('price_range', models.CharField(blank=True, help_text='e.g. ₹1.90 – 2.10 Cr*', max_length=120)),
                ('image', models.ImageField(blank=True, help_text='Floor plan image or interior shot', null=True, upload_to='campaigns/floor_plans/')),
                ('plan_pdf', models.FileField(blank=True, help_text='Downloadable floor plan PDF', null=True, upload_to='campaigns/floor_plans/pdfs/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaigns/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
