# Generated by Django 4.2.29 on 2026-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_seed_prestige_horizon_grand'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brochure_pdf',
            field=models.FileField(blank=True, help_text='Brochure PDF — served after lead form submission', null=True, upload_to='campaigns/brochures/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone number shown on sticky bar and popup, e.g. +919876543210', max_length=20),
        ),
    ]
