# Generated by Django 4.2.29 on 2026-03-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_brochure_pdf_campaign_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='popup_bg_color',
            field=models.CharField(blank=True, help_text='Hex colour for popup header, e.g. #0D2B4E (defaults to navy)', max_length=7),
        ),
        migrations.AddField(
            model_name='campaign',
            name='popup_bg_image',
            field=models.ImageField(blank=True, help_text='Background image for the lead capture popup', null=True, upload_to='campaigns/popup_bg/'),
        ),
    ]
