# Generated by Django 4.2.29 on 2026-03-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_popup_bg_color_campaign_popup_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignamenity',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the amenity', null=True, upload_to='campaigns/amenities/'),
        ),
    ]
