# Generated by Django 4.2.29 on 2026-03-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaignamenity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignamenity',
            name='icon',
        ),
    ]
