# Generated by Django 4.2.29 on 2026-03-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_remove_campaignamenity_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignhighlight',
            name='icon',
        ),
        migrations.AddField(
            model_name='campaignhighlight',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the highlight', null=True, upload_to='campaigns/highlights/'),
        ),
    ]
